### PR TITLE
Add 'note' parameter to coupon codes

### PR DESCRIPTION
**Pull request by MedicOP**
Tested it and it works fine

### CODE REVIEW

**Comment by MedicOP** [comment]
The @SerializedName annotation is probably unnecessary

**Comment by MedicOP** [comment]
why has this not been pulled yet???

**Comment by liam-wiltshire** [comment]
While we appreciate all PRs, we do not guarantee that any specific PR will be merged. With any PR the code has to go through our internal processes, including review, testing and test builds, and as such we are unable to predict timescales for this - likely to be when we are working on other features at the same time.

**Comment by MedicOP** [comment]
It's literally 3 lines of code, how much reviewing and testing do you need for 3 lines of code???????????????????

**Comment by liam-wiltshire** [comment]
Regardless of the code quantity, we have the same internal process to go through. As per my previous message, we will most likely review any/all outstanding PRs when we are next working on the plugin internally.

**Pull request merged**
